name: Android CI (APK)

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.daemon.useFallbackStrategy=auto
      JAVA_TOOL_OPTIONS: -Xms512m -Xmx3g
      ANDROID_HOME: ${{ github.workspace }}/android-sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # --- Install Android Command-line Tools ---
      - name: Install Android cmdline-tools
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          cd $ANDROID_HOME/cmdline-tools
          curl -fo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip -d latest
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

      - name: Accept licenses
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          yes | sdkmanager --licenses

      - name: Install SDK packages
        run: |
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          sdkmanager "platform-tools" \
                     "build-tools;34.0.0" \
                     "platforms;android-34" \
                     "ndk;25.2.9519653" \
                     "cmake;3.22.1"

      - name: Make gradlew executable
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Build Debug APK
        run: |
          if [ -f ./gradlew ]; then
            ./gradlew --no-daemon :main:assembleDebug || ./gradlew --no-daemon assembleDebug
          else
            echo "No gradle wrapper found. Please add Gradle wrapper to the repo." && exit 1
          fi

      - name: Upload Debug APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: |
            **/build/outputs/apk/**/debug/*.apk
            **/outputs/apk/**/debug/*.apk
          if-no-files-found: warn