name: Android CI (APK)

on:
  push:
    branches: [ "**" ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dkotlin.daemon.useFallbackStrategy=auto
      JAVA_TOOL_OPTIONS: -Xms512m -Xmx3g
      ANDROID_HOME: ${{ github.workspace }}/android-sdk
      ANDROID_SDK_ROOT: ${{ github.workspace }}/android-sdk

    steps:
      # Pull repo + submodules (needed for openvpn3 sources)
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      # Host build deps (SWIG used by the OpenVPN3 JNI generation)
      - name: Install host build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y swig

      # --- Install Android command-line tools (puts sdkmanager in PATH) ---
      - name: Install Android cmdline-tools
        run: |
          set -euxo pipefail
          mkdir -p "$ANDROID_HOME/cmdline-tools"
          cd "$ANDROID_HOME/cmdline-tools"
          curl -sSfLo tools.zip https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip
          mv cmdline-tools latest
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> "$GITHUB_PATH"
          echo "$ANDROID_HOME/platform-tools"           >> "$GITHUB_PATH"

      - name: Accept licenses
        run: |
          set -e
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
          yes | sdkmanager --sdk_root="$ANDROID_HOME" --licenses

      - name: Install SDK packages
        run: |
          set -e
          export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"
          sdkmanager --sdk_root="$ANDROID_HOME" \
            "platform-tools" \
            "build-tools;34.0.0" \
            "platforms;android-34" \
            "platforms;android-33" \
            "ndk;25.2.9519653" \
            "ndk;23.2.8568313" \
            "cmake;3.22.1" \
            "cmake;3.10.2.4988404"

      - name: Show modules (for debugging)
        run: |
          echo "===== settings.gradle ====="
          cat settings.gradle || true
          echo "==========================="

      - name: Make gradlew executable
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Build Debug APK
        run: |
          set -e
          if [ -f ./gradlew ]; then
            # Try common launcher modules in order
            ./gradlew --no-daemon :main:assembleDebug \
              || ./gradlew --no-daemon :app:assembleDebug \
              || ./gradlew --no-daemon assembleDebug
          else
            echo "No gradle wrapper found. Please add Gradle wrapper to the repo." && exit 1
          fi

      - name: Upload Debug APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: apk-debug
          path: |
            **/build/outputs/apk/**/debug/*.apk
            **/outputs/apk/**/debug/*.apk
          if-no-files-found: warn