name: Android CI (APK)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # Gradle cache only (keep this)
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # DO NOT cache /usr/local/lib/android/sdk (causes permission errors)
      # Keep a tiny cache for ~/.android if you like
      - name: Cache ~/.android (licenses only)
        uses: actions/cache@v4
        with:
          path: ~/.android
          key: ${{ runner.os }}-android-licenses-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-licenses-

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android cmdline-tools
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      # Install only what the build needs (adjust if you change compile/target/ndk)
      - name: Install required SDK packages
        run: |
          sdkmanager --install \
            "platforms;android-35" \
            "platform-tools" \
            "build-tools;35.0.0" \
            "cmake;3.22.1" \
            "ndk;28.0.13004108"

      - name: Enable AndroidX in gradle.properties
        run: |
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
          # Give Gradle more heap; helps packaging step
          echo "org.gradle.jvmargs=-Xmx3g -Dkotlin.daemon.jvm.options=-Xmx2g" >> gradle.properties
          # Keep regular build cache ON, config cache OFF (SWIG task incompatible)
          echo "org.gradle.caching=true" >> gradle.properties
          echo "org.gradle.configuration-cache=false" >> gradle.properties

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK (XuiOvpn23 only)
        run: |
          ./gradlew :main:assembleXuiOvpn23Debug \
            --no-daemon --no-configuration-cache --build-cache -Dorg.gradle.caching=true \
            --stacktrace --info

      # Always upload reports and the APK
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            build/reports/**
            main/build/reports/**
            main/build/outputs/**

      - name: Upload Debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AIOVPN-XuiOvpn23-Debug
          path: main/build/outputs/apk/xuiOvpn23/debug/*.apk
