name: Android CI (APK)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Avoid running multiple builds for the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # ---------- CACHES ----------
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            /usr/local/lib/android/sdk
          key: ${{ runner.os }}-android-${{ hashFiles('**/build.gradle*', '.github/workflows/android-ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-android-
      # ---------------------------

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android cmdline-tools
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      - name: Make gradlew executable
        run: chmod +x gradlew

      # Build ONLY the UI + ovpn23 flavor; Gradle build cache enabled
      - name: Build Debug APK (UiOvpn23 only)
        run: |
          ./gradlew :main:assembleUiOvpn23Debug \ -Dorg.gradle.configuration-cache=false --no-configuration-cache
            --no-daemon --build-cache \
            -Dorg.gradle.caching=true

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: AIOVPN-UiOvpn23-Debug
          path: main/build/outputs/apk/uiOvpn23/debug/*.apk
