name: Android CI (APK)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      # ---------- CACHES ----------
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            /usr/local/lib/android/sdk
          key: ${{ runner.os }}-android-${{ hashFiles('**/build.gradle*', '.github/workflows/android-ci.yml') }}
          restore-keys: |
            ${{ runner.os }}-android-
      # ---------------------------

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Install Android cmdline-tools
        uses: android-actions/setup-android@v3

      - name: Accept Android licenses
        run: yes | sdkmanager --licenses || true

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK (XuiOvpn23)
        env:
          # Extra heap to avoid OOM during packaging
          GRADLE_OPTS: "-Xmx3g -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError"
        run: |
          ./gradlew :main:assembleXuiOvpn23Debug \
            --no-daemon --no-configuration-cache --build-cache \
            -Dorg.gradle.caching=true \
            --stacktrace --info

      # Always upload reports and any produced APKs (even on failure)
      - name: Upload build reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: |
            build/reports/**
            main/build/reports/**
            main/build/outputs/**

      - name: Upload Debug APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: AIOVPN-XuiOvpn23-Debug
          path: main/build/outputs/apk/xuiOvpn23/debug/*.apk
