name: Android CI (APK)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: true

      # ---------- CACHES ----------
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache Android SDK
        uses: actions/cache@v4
        with:
          path: |
            ~/.android
            /usr/local/lib/android/sdk
          key: ${{ runner.os }}-android-${{ hashFiles('**/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-android-
      # ---------------------------

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install host build deps
        run: sudo apt-get update && sudo apt-get install -y libc6 libstdc++6

      - name: Install Android cmdline-tools
        uses: android-actions/setup-android@v3

      - name: Accept licenses
        run: yes | sdkmanager --licenses || true

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK (:main only)
        run: ./gradlew :main:assembleDebug --build-cache

      - name: Upload Debug APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: main/build/outputs/apk/debug/*.apk
